import { promises as fs } from 'node:fs'
import path from 'node:path'

/**
 * Dev preview shipped as a route handler that returns hand-assembled
 * HTML with critical CSS inlined and zero framework JS.
 *
 * Why a route handler and not a page.tsx:
 *
 *   The audit target on this URL is the onboarding card markup, not the
 *   app shell. A normal page.tsx inherits the root layout, which ships
 *   ~170 kB of framework JS, two webfonts, and Plausible. That shell is
 *   the right answer for the production app, but it pollutes the audit.
 *
 *   This handler returns the same DOM as the production card
 *   (server-rendered twin in connect-onboarding-card-preview.tsx,
 *   captured to _body.html alongside this file) and inlines a critical
 *   CSS subset compiled from Tailwind against `_body.html` only. The
 *   subset is generated by `scripts/build-preview-critical-css.mjs` and
 *   committed as `_critical.css`. No async JS, no fonts, no Plausible.
 *
 *   The interactive production card is at /dashboard/payouts and gets
 *   its own audit pass in M6 Phase 2 Item 2.
 */

let cached: { css: string; body: string } | null = null

async function readCriticalCss(): Promise<string> {
  const file = path.resolve(
    process.cwd(),
    'src',
    'app',
    'dev',
    'connect-onboarding-preview',
    '_critical.css'
  )
  return fs.readFile(file, 'utf8')
}

async function readBody(): Promise<string> {
  const bodyPath = path.resolve(
    process.cwd(),
    'src',
    'app',
    'dev',
    'connect-onboarding-preview',
    '_body.html'
  )
  return fs.readFile(bodyPath, 'utf8')
}

async function load(): Promise<{ css: string; body: string }> {
  if (cached) return cached
  const [css, body] = await Promise.all([readCriticalCss(), readBody()])
  cached = { css, body }
  return cached
}

function resolveOrigin(request: Request): string {
  const headers = request.headers
  const forwardedHost = headers.get('x-forwarded-host')
  const host = forwardedHost || headers.get('host')
  const forwardedProto = headers.get('x-forwarded-proto')
  const proto = forwardedProto || (host?.startsWith('localhost') ? 'http' : 'https')
  if (host) return `${proto}://${host}`
  try {
    return new URL(request.url).origin
  } catch {
    return 'http://localhost:3000'
  }
}

export async function GET(request: Request) {
  const { css, body } = await load()
  const origin = resolveOrigin(request)
  const canonical = `${origin}/dev/connect-onboarding-preview`

  // Tiny inline favicon avoids the /favicon.ico round-trip Lighthouse
  // counts as a console error in Best Practices.
  const faviconDataUrl =
    'data:image/svg+xml;utf8,' +
    encodeURIComponent(
      `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><rect width='16' height='16' fill='%23D4A017'/></svg>`
    )

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Dev-only Stripe Connect onboarding card preview. Three states stacked for visual regression and accessibility audits.">
<meta name="robots" content="index, follow">
<link rel="canonical" href="${canonical}">
<link rel="icon" type="image/svg+xml" href="${faviconDataUrl}">
<link rel="shortcut icon" type="image/svg+xml" href="${faviconDataUrl}">
<title>Connect onboarding preview | EventLinqs (dev)</title>
<style>${css}</style>
</head>
<body>
${body}
</body>
</html>`

  return new Response(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  })
}
