import { NextRequest, NextResponse } from 'next/server'
import { getOrganiserEvent, fetchEventAttendees } from '@/lib/reporting/attendees'
import {
  buildAttendeesCsv,
  buildAttendeesXlsx,
  buildDoorListPdf,
} from '@/lib/reporting/exporters'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

type Props = { params: Promise<{ id: string }> }

/**
 * One-click attendee exports: CSV and XLSX carry the full granular guest list
 * for CRM or email import; PDF is the simplified, printable door list for
 * event day. Ownership is verified first (getOrganiserEvent fails closed), so
 * an organiser can never export another organiser's attendees.
 */
export async function GET(request: NextRequest, { params }: Props) {
  const { id } = await params
  const format = (request.nextUrl.searchParams.get('format') ?? 'csv').toLowerCase()

  const event = await getOrganiserEvent(id)
  if (!event) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const attendees = await fetchEventAttendees(id)
  const datePart = event.startDate.slice(0, 10)
  const base = `${event.slug || 'event'}-attendees-${datePart}`

  if (format === 'csv') {
    return new NextResponse(buildAttendeesCsv(attendees), {
      status: 200,
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="${base}.csv"`,
        'Cache-Control': 'no-store',
      },
    })
  }

  if (format === 'xlsx') {
    const buffer = await buildAttendeesXlsx(attendees)
    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${base}.xlsx"`,
        'Cache-Control': 'no-store',
      },
    })
  }

  if (format === 'pdf') {
    const eventDateLabel = new Intl.DateTimeFormat('en-AU', {
      weekday: 'short',
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
      timeZone: event.timezone ?? undefined,
      timeZoneName: 'short',
    }).format(new Date(event.startDate))
    const generatedLabel = `Generated by EventLinqs on ${new Intl.DateTimeFormat('en-AU', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      timeZone: event.timezone ?? undefined,
    }).format(new Date())}. You own this data.`
    const pdf = await buildDoorListPdf(attendees, {
      eventTitle: event.title,
      eventDateLabel,
      organisationName: event.organisationName,
      generatedLabel,
    })
    return new NextResponse(pdf as unknown as BodyInit, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${base}-door-list.pdf"`,
        'Cache-Control': 'no-store',
      },
    })
  }

  return NextResponse.json({ error: 'Unsupported format' }, { status: 400 })
}
